### ISSUE TITLE
error on failing to login

### ISSUE THREAD

**Issue by ty-a** [ty-a/GEMWbot2#34]
Exception in thread "Thread-18" java.lang.AssertionError: Unreachable!
        at org.wikipedia.Wiki.login(Wiki.java:1246)
        at com.faceyspacies.GEMWbot.BaseWikiTask.Login(BaseWikiTask.java:227)
        at com.faceyspacies.GEMWbot.GrandExchangeUpdater.doUpdates(GrandExchangeUpdater.java:183)
        at com.faceyspacies.GEMWbot.GrandExchangeUpdater.Start(GrandExchangeUpdater.java:132)
        at com.faceyspacies.GEMWbot.BaseWikiTask.run(BaseWikiTask.java:204)
        at com.faceyspacies.GEMWbot.GrandExchangeUpdater.run(GrandExchangeUpdater.java:1)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ty-a** [comment]
https://github.com/ty-a/GEMWbot2/commit/3c5f08d9aaf0fad262fcf21925fa10b1f609d901 fixed in that
