### ISSUE TITLE
NullPointer before updating GEPrices/data and LastPrices/data rarely

### ISSUE THREAD

**Issue by ty-a** [ty-a/GEMWbot2#36]
`java.lang.NullPointerException
    at com.faceyspacies.GEMWbot.BaseWikiTask.loadCurPrice(BaseWikiTask.java:369)

    at com.faceyspacies.GEMWbot.GrandExchangeUpdater.getTodaysEpochTimestamp(GrandExchangeUpdater.java:577)

    at com.faceyspacies.GEMWbot.GrandExchangeUpdater.Start(GrandExchangeUpdater.java:161)

    at com.faceyspacies.GEMWbot.BaseWikiTask.run(BaseWikiTask.java:206)

    at com.faceyspacies.GEMWbot.GrandExchangeUpdater.run(GrandExchangeUpdater.java:1)

    at java.base/java.lang.Thread.run(Thread.java:844)
`

**Comment by ty-a** [comment]
https://github.com/ty-a/GEMWbot2/blob/master/src/com/faceyspacies/GEMWbot/GrandExchangeUpdater.java#L579

We should check for null in https://github.com/ty-a/GEMWbot2/blob/master/src/com/faceyspacies/GEMWbot/GrandExchangeUpdater.java#L161

This is likely because of a race condition on the rate limit of Jagex's API. So we could either wait a few seconds to ensure we won't hit the rate limit in addition to checking for null, or just check for null and then wait as needed.
